routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
/* Home */

Auth::routes(['register' => false]);

Route::get('/documentacion', 'DocumentacionController@index')->name('documentacion');

Route::get('/', 'WebController@index')->name('welcome');

/*System*/

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'admin'], 'namespace' => 'System'], function () {
    Route::resources([
        'category' => 'CategoryController',
        'product' => 'ProductController',
        'user' => 'UsersController',
    ]);

});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;
    
    public $table = 'categories';
    protected $dates = ['created_at', 'updated_at','deleted_at'];
    protected $fillable = ['name', 'imagename', 'status','created_at', 'updated_at','deleted_at'];


    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/System/CategoryController.php
<?php

namespace App\Http\Controllers\System;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Support\Facades\Storage;

class CategoryController extends Controller
{

    public function index()
    {
        $category = Category::paginate(5);

        return view('category.index', compact('category'));
    }

    public function create()
    {
        return view('category.create');
    }

    public function store(CategoryRequest $request)
    {
        $input = $request->all();

        if ($request->hasFile('imagename')) {

        $input['imagename'] = $request->imagename->store('img_category', 'public');

        }

        Category::create($input);

        return redirect()->route('category.index')->with('success', 'Category created successfully.');

    }

    public function show(Category $category)
    {
        return view('category.show', compact('category'));
    }

    public function edit(Category $category)
    {
        return view('category.edit', compact('category'));
    }

    public function update(CategoryRequest $request, Category $category)
    {

        if ($request->hasFile('imagename')) {

            Storage::delete($category->imagename);

            $category->imagename = $request->imagename->store('img_category', 'public');
        }

        $category->name = $request->name;

        $category->save();

        return redirect()->route('category.index')->with('success', 'Category updated successfully.');
    }

    public function destroy(Category $category)
    {
        Storage::delete($category->imagename);

        $category->delete();

        return redirect()->route('category.index')->with('success', 'Successful removal.');
    }

}

resources/views/category/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-9">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-lg-11">
                            <h2>Categorías</h2>
                        </div>
                        <div class="col-lg-1">
                            <a class="btn btn-primary" href="{{ url('category') }}"> Back</a>
                        </div>
                    </div>
                </div>

                @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
                @endif

                <div class="card-body">
                    <form action="{{ route('category.store') }}" method="POST" accept-charset="UTF-8"
                        enctype="multipart/form-data">
                        @csrf

                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Name:</strong>
                                    <input type="text" name="name" class="form-control" placeholder="Name">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Imagen:</strong>
                                    <input type="file" name="imagename" id="imagename">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/category/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-9">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-lg-11">
                            <h2>Categorías</h2>
                        </div>
                        <div class="col-lg-1">
                            <a class="btn btn-primary" href="{{ url('category') }}"> Back</a>
                        </div>
                    </div>
                </div>

                @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
                @endif
                <div class="card-body">
                    <form action="{{ route('category.update', $category->id) }}" method="POST" accept-charset="UTF-8"
                        enctype="multipart/form-data">
                        @method('PATCH')
                        @csrf
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Name:</strong>
                                    <input type="text" name="name" class="form-control" placeholder="Name" value="{{ $category->name }}">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Imagen:</strong>
                                    <input type="file" name="imagename" id="imagename">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/category/index.blade.php
<!-- HTML for static distribution bundle build -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>API Documentation}</title>

    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400|Crimson+Text' rel='stylesheet' type='text/css'>
    <!-- Normalize -->
    <link type="text/css" href="/css/normalize.css" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="/libs/bootstrap-3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Source+Code+Pro:300,600|Titillium+Web:400,600,700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/swagger/swagger-ui.css" >
    <link rel="icon" type="image/png" href="../favicon.ico">

    <style>
        .swagger-ui .info .title small pre {
            background: transparent;
            border: 0;
            color: white;
            padding: 0;
        }
        body{
            overflow-x: hidden;
        }
        .swagger-ui .model-box, .opblock-section-header, .swagger-ui .responses-inner {
              overflow-x: scroll;
        }
    </style>
</head>

<body>
    <div class="container">
        <div id="swagger-ui"></div>
    </div>

    <script src="/swagger/swagger-ui-bundle.js"> </script>
    <script src="/swagger/swagger-ui-standalone-preset.js"> </script>
    <script>
        window.onload = function() {
            // Build a system
            const ui = SwaggerUIBundle({
                url: "/swagger/swagger.json",
                dom_id: '#swagger-ui',
                deepLinking: true,
                presets: [
                    SwaggerUIBundle.presets.apis,
                    SwaggerUIStandalonePreset
                ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
    //    layout: "StandaloneLayout"
            })

            window.ui = ui
        }
    </script>
</body>
</html>

resources/views/category/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-9">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-lg-11">
                            <h2>Categorías</h2>
                        </div>
                        <div class="col-lg-1">
                            <a class="btn btn-primary btn-sm" href="{{ url('category') }}"> Back</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-bordered table-sm">
                        <tr>
                            <th>First Name:</th>
                            <td>{{ $category->name }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="text-center py-3">
                    @if(!isset($category->imagename))
                    <img style="width:15em;height:15em;" src="{{url('storage/img_category/default.png')}}"
                        class="avatar" alt="avatar">
                    @else
                    <img style="width:15em;height:15em;" src="{{url('storage/'.$category->imagename)}}"
                        class="avatar">
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

@endsection